# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00ec894b8f00bc4759161c4ef7b2f9ffa900063a300464b16b88fdba099eeeb66570472c5c0bc8bcc78a11b44143ba6e8aad112753693f1d6ebd559376bdcc61

test:
  secret_key_base: adbc54701bd67f51ef4696402c49099885ab9ffdd198b65988623ec52f1c2a42839cc897114c15f72ab0753efc946b58ba821f07eec70a28058bdc9766cdcb31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
